[package]
name = "tracker"
version = "0.1.0"
description = "Basic time tracker for tasks and projects"
edition = "2021"

[lib]
name = "tracker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-log = "2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
tracker-core = { path = "../crates/tracker-core" }

